#!/data/data/com.termux/files/usr/bin/bash
varname=$(basename $PREFIX/var/lib/proot-distro/installed-rootfs/ubuntu/home/*)
proot-distro login ubuntu --user $varname --shared-tmp -- env DISPLAY=:1.0 $@

