#!/data/data/com.termux/files/usr/bin/bash

killall -9 termux-x11 Xwayland pulseaudio
termux-wake-lock; termux-toast "Starting X11"

XDG_RUNTIME_DIR=${TMPDIR} termux-x11 :1.0 & > /dev/null 2>&1
sleep 1

am start --user 0 -n com.termux.x11/com.termux.x11.MainActivity
sleep 1

MESA_NO_ERROR=1 MESA_LOADER_DRIVER_OVERRIDE=zink TU_DEBUG=noconform MESA_GL_VERSION_OVERRIDE=4.6COMPAT MESA_GLES_VERSION_OVERRIDE=3.2 virgl_test_server_android --angle-gl & > /dev/null 2>&1
env DISPLAY=:1.0 dbus-launch --exit-with-session xfce4-session & > /dev/null 2>&1